name: Gradle Assemble
on: [pull_request]

jobs:
  assemble:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 11 ]
        os: [ubuntu-latest, windows-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@main
        with:
          upgrade-qemu: true
      - name: Run Gradle (assemble)
        if: ${{ runner.os == 'Windows' }}
        run: |
          ./gradlew assemble -x :distribution:docker:buildArm64DockerImage -x :distribution:docker:buildDockerImage -x :distribution:docker:buildPpc64leDockerImage --parallel --no-build-cache -PDISABLE_BUILD_CACHE
      - name: Run Gradle (assemble)
        if: ${{ runner.os != 'Windows' }}
        run: |
          ./gradlew assemble --parallel --no-build-cache -PDISABLE_BUILD_CACHE
